---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: jobs
---
apiVersion: v1
kind: Namespace
metadata:
  name: services
---
apiVersion v1
kind: Namespace
metadata:
  name: logging